[workspace]
members = [
    "crates/postgres_dataload",
    "crates/pdf_processing",
    "crates/get_data",
    "crates/ml_bid_predictor",
    "crates/ai_summary",
    "crates/sns_notification",
    "crates/etenders_scraper"
]
resolver = "2"
